export const message = {
  //* users
  register_success: 'Register success',
  register_faild: 'Register failed',
  login_success: 'Login success',
  login_faild: 'Login failed',
  get_user_success: 'Get user success',
  get_user_faild: 'Get user failed',
  get_user_detail_success: 'Get user detail success',
  get_user_detail_faild: 'Get user detail failed',
  update_user_success: 'Update user success',
  update_user_faild: 'Update user failed',
  delete_user_success: 'Delete user success',
  delete_user_faild: 'Delete user failed',
  upload_avatar_success: 'Upload avatar success',
  upload_avatar_faild: 'Upload avatar failed',
  data_invalid: 'Data invalid',
  email_or_username_exist: 'Email or Username exist',
  username_not_exist: 'Username not exist',
  email_not_exist: 'Email not exist',
  password_invalid: 'Password invalid',
  id_not_exist: 'ID not exist',
  not_logged_in: 'You are not logged in',
  error_authentication: 'Authentication failed',
  error_authorization: 'Authorization failed',
  incorrect_password: 'Incorrect password',
  extension_file_invalid: 'Extension file invalid',

  //* user_statuses
  get_user_status_success: 'Get user status success',
  get_user_status_faild: 'Get user status failed',
  get_user_status_detail_success: 'Get user status detail success',
  get_user_status_detail_faild: 'Get user status detail failed',
  update_user_status_success: 'Update user status success',
  update_user_status_faild: 'Update user status failed',

  //* friendship
  create_friendship_success: 'Create friendship success',
  create_friendship_faild: 'Create friendship failed',
  get_friendship_success: 'Get friendship success',
  get_friendship_faild: 'Get friendship failed',
  get_friendship_detail_success: 'Get friendship detail success',
  get_friendship_detail_faild: 'Get friendship detail failed',
  update_friendship_success: 'Update friendship success',
  update_friendship_faild: 'Update friendship failed',
  delete_friendship_success: 'Delete friendship success',
  delete_friendship_faild: 'Delete friendship failed',
  friendship_existed: 'Friendship existed',
  friendship_not_existed: 'Friendship not existed'
} as const
